#!/bin/bash 

python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
python whetlab_execute.py gpu
